### ISSUE TITLE
Dueling network with atari

### ISSUE THREAD

**Issue by sandaz9** [keras-rl/keras-rl#113]
I'm using the dueling dqn with atari environnment. 
After creating the neural network, I have an error :  

`model = Sequential()
model.add(Lambda(lambda a: a / 255.0,input_shape=(minecraft_resolution[0],minecraft_resolution[1],3)))
model.add(Permute((3, 1, 2)))
model.add(Conv2D(32, (8, 8), strides=(2, 2), activation=activation))
model.add(Conv2D(32, (4, 4), strides=(2, 2), activation=activation))
model.add(Conv2D(32, (3, 3), strides=(2, 2), activation=activation))
model.add(Conv2D(32, (2, 2), strides=(1, 1), activation=activation))
model.add(TimeDistributed(Flatten()))
model.add(LSTM(128))
for i in xrange(nb_layers):
    model.add(Dense(hidden_size, activation=activation))
model.add(Dense(env.action_space.n + 1))
model.add(Lambda(lambda a: K.expand_dims(a[:, 0], axis=-1) + a[:, 1:], output_shape=(env.action_space.n,)))

...

memory = SequentialMemory(limit=10000000, window_length=1)
agent = DQNAgent(model=model, nb_actions=nb_actions, memory=memory, nb_steps_warmup=10,
enable_dueling_network=True, dueling_type='avg', target_model_update=1e-3, policy=policy,processor=processor)
agent.compile(optimizer, metrics=['mse'])
...

`

ValueError: Error when checking : expected input_1 to have 4 dimensions, but got array with shape (1, 1, 200, 200, 3)
I think it's because the neural network is trained with a batch.  

def process_observation(self, observation):
        return(imresize(observation,(200,200)).shape)
the shape is (200, 200, 3)

**Comment by shoCaffeTeria** [comment]
I have the same error. Did you fix it?

**Comment by latex123** [comment]
what problem?



At 2018-01-19 21:27:30, "shoCaffeTeria" <notifications@github.com> wrote:


I have the same error. Did you fix it?

**Comment by shoCaffeTeria** [comment]
input_shape=(224,224,3)

model.add(Conv2D(32,3,3,input_shape=input_shape))
....

I tried to train the model with DQNAgent  on my  own env.but I have an error
ValueError: Error when checking : expected input_1 to have 4 dimensions, but got array with shape (1, 1, 224, 224, 3)

what happened?

**Comment by ChristianGonzalez** [comment]
I am having the same issue. Was this ever solved?

**Comment by DevanshBesain** [comment]
The problem is that the emulator returns observation of shape (1,1,224,224,3) which when passed to your input (shape ?,224,224,3) causes a value error due to dimension mismatch try changing input shape to 

> input_shape=(1,height,width,channel) 

now your input must expect a shape of (?,1,224,224,3) note that the extra dimension we add here represents the window of sequence observed for storing in the memory which we set using "window_length=1" parameter in  SequentialMemory

**Comment by AloshkaD** [comment]
@DevanshBesain Doing so generates a new error 

Input 0 is incompatible with layer conv2d_1: expected ndim=4, found ndim=5

**Comment by vhutse** [comment]
Has anybody been able to solve this? @sandaz9 @shoCaffeTeria @AloshkaD @ChristianGonzalez 

I'm having the same issue. Once I try using more than one channel in the input shape, I can't seem to get it to work properly.

1)  When using input shape: (window_length, channels, height, width):
"ValueError: Input 0 is incompatible with layer conv2d_1: expected ndim=4, found ndim=5"

2) When using input shape: (channels, height, width):
"ValueError: Error when checking input: expected conv2d_1_input to have 4 dimensions, but got array with shape (1, 1, 3, 4, 1)"
Note: Width is 1 because the problem is still scaling up. Using 1DConv is not a solution.

It does work fine when only using 1 channel.

**Comment by NathanBWaters** [comment]
Yeah I don't understand why this library is adding dimensions to the state that we've provided.

**Comment by NathanBWaters** [comment]
So for me this is what I'm seeing using DQNAgent.  
My observation shape is (5, 337, 513, 3).

The following line wraps the observation in a list:
https://github.com/keras-rl/keras-rl/blob/master/rl/agents/dqn.py#L647
```state = self.memory.get_recent_state(observation)```

This line then wraps it in another list:
https://github.com/keras-rl/keras-rl/blob/master/rl/agents/dqn.py#L69
```q_values = self.compute_batch_q_values([state]).flatten()```

This line then takes the doubly-wrapped list and returns it as a numpy array:
https://github.com/keras-rl/keras-rl/blob/master/rl/agents/dqn.py#L63
```batch = self.process_state_batch(state_batch)```
batch.shape is (1, 1, 5, 337, 513, 3) at this point

Now, it would typically error on `self.model.predict_on_batch(batch)`, but would work great if at this point it instead had `self.model.predict_on_batch(batch[0])`.  

Current solution: I'm going to inherit from the DQN class and override one the methods so that it's not adding all one of the two extra dimensions.

**Comment by NathanBWaters** [comment]
Simple fix:

```class WrapperAgent(DQNAgent):
    '''
    Overriding the DQNAgent method that is causing a bug
    '''
    def compute_q_values(self, state):
        '''
        I'm solving this bug: https://github.com/keras-rl/keras-rl/issues/113
        '''
        q_values = self.compute_batch_q_values(state).flatten()
        assert q_values.shape == (self.nb_actions,)
        return q_values
```

**Comment by NathanBWaters** [comment]
You can remove a dimension by using your own processor.
```class CustomProcessor(Processor):
    '''
    acts as a coupling mechanism between the agent and the environment
    '''

    def process_state_batch(self, batch):
        '''
        Given a state batch, I want to remove the second dimension, because it's
        useless and prevents me from feeding the tensor into my CNN
        '''
        return numpy.squeeze(batch, axis=1)

```
