### ISSUE TITLE
Training is not using 100% CPU

### ISSUE THREAD

**Issue by codetiger** [keras-rl/keras-rl#120]
I am running the examples on my Ubuntu machine Intel® Core i7-4770K CPU @ 3.50GHz with 4 cores. During the entire training, only ~25% of the CPU is used. Which means it is running on only one core. Am I missing something?

**Comment by M00NSH0T** [comment]
I know this is necro, but I figure since we're kicking new life into this, may as well revisit some of these open threads.  

I could be wrong, but my understanding of why this seems to happen is that you'd need to use an async agent like A3C or async DDPG or whatever to make use of all possible threads on your processor. If you're using the cpu version of tensorflow, it should utilize most of your CPU to train the neural networks, but unlike with traditional machine learning, the neural networks only get updated after your environment takes a step, and that training is only for a sample size of 1, so that part can run pretty quickly and may just show up on your CPU load as a quick peak. The environment you're using may be rather CPU intense (like mine has to a ton of math each step), and unless your environment is multi-threading somehow, that's just going to run on one CPU.  A3C and other asynchronous algorithms will create multiple actor/critic pairs that will run in parallel with one another, so with those, you can use your full CPU (and GPU) potential. That's why they're so popular, and why I want to get async DDPG built here.
