### ISSUE TITLE
DQN learning plateaus too early

### ISSUE THREAD

**Issue by ionelhosu** [keras-rl/keras-rl#146]
Hi! I performed some experiments with this implementation and at first I was happy to saw that it's the fastest I know, at least on my hardware. However, I found that it only reaches a score of about 40 in Breakout after ~two million steps and doesn't improve  from there, even after 50 million. I ran the standard DQN architecture / hyperparameters that was published in Nature. Did anyone else experience this problem? Thank you!

**Comment by chairbender** [comment]
This repo is dead. Might want to try tensorforce instead.

**Comment by ppwwyyxx** [comment]
Has tensorforce reproduced any good score on breakout?

**Comment by chairbender** [comment]
Nobody has posted benchmarks for the breakout environment. But if I had to guess, I would bet on tensorforce over this library. Either way, you're likely to get actual responses over there rather than here. 

You may also want to look into openai / baselines, as they are trying to reproduce published results. I think that repo is also still active. See this blog. It directly mentions breakout and shows benchmarks: https://blog.openai.com/openai-baselines-dqn/
