### ISSUE TITLE
Parallel training with keras-rl

### ISSUE THREAD

**Issue by jasonzliang** [keras-rl/keras-rl#151]
I am running the ddpg agent and I notice that it is only making use of a single thread. Is there any version of keras-rl which can make use of mutliple cores for gathering samples from the environment?

**Comment by lemonteaa** [comment]
Not now as far as I am aware of, although there are efforts underway by some people (such as @ParthaEth , kudos to you :wink: ).

Personally, I believe that in the long run it would probably be better to review this library's architecture, especially the `Agent` base class, since as @matthiasplappert mentions there are recent advances such as A3C that challenges the assumption there. (And maybe that's not going to be the last innovation in the architectural front, for example, see [this OpenAI blog entry](https://blog.openai.com/learning-to-cooperate-compete-and-communicate/).)

**Comment by chairbender** [comment]
You may want to look into tensorforce as an alternative to this. Tensorforce is actively developed and this one is dead.

**Comment by mattdornfeld** [comment]
@Jazonzliang I found success having a single environment spawn of several multiprocessing workers.
