### ISSUE TITLE
Simplest possible example

### ISSUE THREAD

**Issue by bkj** [keras-rl/keras-rl#18]
I'm trying to get intuition about how these models work, and I was trying to train a model to learn the (seemingly) simplest possible policy:

https://github.com/openai/gym/blob/master/gym/envs/debugging/one_round_deterministic_reward.py

Adapting from the `cartpole` example, I tried:

```
model = Sequential()
model.add(Dense(2, input_shape=(1,)))
model.add(Dense(nb_actions, activation='sigmoid'))

memory = SequentialMemory(limit=50000)
policy = BoltzmannQPolicy()
dqn = DQNAgent(
    model=model, 
    nb_actions=nb_actions, 
    memory=memory, 
    nb_steps_warmup=10,
    target_model_update=1e-2, 
    policy=policy
)
dqn.compile(Adam(lr=1e-3), metrics=['mae'])

dqn.fit(env, nb_steps=10000, visualize=False, verbose=2)
dqn.test(env, nb_episodes=10, visualize=False)
```

This doesn't really seem to learn the optimal policy of `action = 1`.  Any thoughts as to what I'm doing wrong here?

Thanks
Ben

**Comment by SimonRamstedt** [comment]
Hey Ben,

Thanks for testing! That's actually a quite tricky issue you uncovered there.

At first you generally shouldn't have a sigmoid at the output of the Q-function because it restricts the Q values to be between 0 and 1 (for this special environment it doesn't make a difference because the Q values happen to be just between 0 and 1). And in the layer before you should have a nonlinearity:
```
model.add(Dense(2, input_shape=(1,), activation='sigmoid'))
model.add(Dense(nb_actions))
```

But even after changing this the problem remains. That's because in DQN has two policies: An *exploration policy* which is in this case the BoltzmanQPolicy (which consists in selecting an action with a probability proportional to the exp of its Q-value) and the *exploitation policy*. The exploitation policy always consists in taking the action with the highest Q-value. During learning the exploitation policy is used to select the actions the agent takes in the environment (but for not for learning the Q-function). Usually at test time (`dqn.test(...)` )  the exploitation policy should be used to select the actions. Then you'd always get `a = 1`. This isn't happening here and probably will be fixed in the future ( @matthiasplappert ).

But it's still weird to see the BoltzmanQPolicy perform so badly (b.t.w. the epsilon greedy with a small epsilon works much better). The reason for this is that the BoltzmanQPolicy is not invariant to the scale of the Q values (other than epsilon greedy). To obtain the same results across different scales of the Q values the `tau` parameter has to be scaled proportionally to Q. So if you try
```
policy = BoltzmannQPolicy(tau=0.05) 
```
you'll get almost every time `a=1` (and therefore reward = 1).

**Comment by yongduek** [comment]
It seems that the policy used during the test is still BoltzmannQPolicy.

I was wondering whether the use of the Greedy Policy (taking action of the highest Q) during test time should have been hard coded or set as default.

**Comment by matthiasplappert** [comment]
I think maybe we need the ability to specify a distinct train and test policy. The reason why DQN isn't implemented to always select the action with the maximum Q value is simply that, for some environments like Atari, the agent can get stuck. Using an eps-greedy policy with say `eps = 0.05` ensures that the agent takes random actions frequently enough to get "unstuck" eventually.

I would therefore suggest the following: in `__init__`, add a new parameter `test_policy=None`. If it is set to `None`, use `policy` during test time. If not, use `test_policy` during test time. This should be flexible enough and still allows one to use the same policy during train and test time easily. What do you guys think?

Also, like @SimonRamstedt pointed out, Boltzmann is tricky to get right. The temperature is important and it's much harder to chose than the eps parameter of the eps greedy policy since its less intuitive.

**Comment by yongduek** [comment]
I think @matthiasplappert provided quite a good and reasonable policy ^^

**Comment by bhimaras** [comment]
> The reason why DQN isn't implemented to always select the action with the maximum Q value during test time is simply that, for some environments like Atari, the agent can get stuck

Hi matthiasplappert/ others, 

Can someone explain to me why the agent can get stuck during testing?! 

I implemented dqn using keras, openai gym and I'm currently training it for the breakout game. I'm observing that during testing the paddle sometimes get stuck to one side and nothing happens anymore (I have to restart testing). Note that during testing I don't have any eps...the agent takes the action corresponding to the best Q value.
