### ISSUE TITLE
any example of passing RGB image in Keras-RL?

### ISSUE THREAD

**Issue by reinforcelearn** [keras-rl/keras-rl#238]
I am running into an [issue](https://github.com/keras-rl/keras-rl/issues/229) where Keras-RL is adding an extra dimension to my RGB input. When I set the input_shape along with Window_Length, I get error from Keras:
_ValueError: Input 0 is incompatible with layer conv2d_1: expected ndim=4, found ndim=5_

When I pass the input shape with Window_Length, I get an error from Keras-RL fit function:
_ValueError : Error when checking input: expected input_1 to have 4 dimensions, but got array with shape (1,1,3,144,256)_

Can someone point me to an example where they have trained an agent using an RGB image with Keras-RL?

**Comment by thejhonnyguy** [comment]
I think the usual procedure is the convert the RGB image to grayscale, hence removing a dimension.
A practical implementation of an agent in an RGB environment is here. (I haven't trained it myself, but it's an example for everyone).
https://github.com/keras-rl/keras-rl/blob/master/examples/dqn_atari.py
This also involves using the history frames in place of the RGB channels. In your case you appear to pass 1 history frame (no history, only current, inferring from `(1, 1, 3, 144, 256)`, the second `1`). In this case your CNN may have `channels_first` with `1` channel, shape `(?, 1, 144, 256)`, OR, `channels_first` with `3` channels (RGB) since you're not utilising history `(?, 3, 144, 256)`.

*Note: I'm inferring `(Batch Size, History, RGB, Pixels, Pixels)`*

Here is a little snippet from the attached sample (line 24 to 31)
```py
class AtariProcessor(Processor):
    def process_observation(self, observation):
        assert observation.ndim == 3  # (height, width, channel)
        img = Image.fromarray(observation)
        img = img.resize(INPUT_SHAPE).convert('L')  # resize and convert to grayscale
        processed_observation = np.array(img)
        assert processed_observation.shape == INPUT_SHAPE
        return processed_observation.astype('uint8')  # saves storage in experience memory
```

**Comment by mirraaj** [comment]
@reinforcelearn, @thejhonnyguy Is this issue solved?

**Comment by petrosgk** [comment]
You can use a custom `Processor` and override `process_state_batch()`  to convert the batch of RGB states with shape `(batch_size, history, height, width, channels)` returned by keras-rl to a batch of RGB states with the dimensions expected by the CNN. 

You can go through each state in the batch, convert it to an RGB state of shape `(height, width, history * channels)` and then concatenate them into a batch with shape `(batch_size, height, width, history * channels)`

Here's how I am doing it:
```python
  def process_state_batch(self, batch):
    if not opt.grayscale:
      batch_samples = []
      for batch_sample in range(batch.shape[0]):
        sequence = []
        for frame in range(batch.shape[1]):
          sequence.append(batch[batch_sample][frame])
        sequence = np.concatenate(sequence, axis=-1)
        sequence = np.expand_dims(sequence, axis=0)
        batch_samples.append(sequence)
      batch = np.concatenate(batch_samples, axis=0)
    else:
      batch = np.transpose(batch, [0, 2, 3, 1])
    batch = batch.astype(np.float32) / 255.0
    return batch
```
