### ISSUE TITLE
DQNAgent has no attribute optimizer

### ISSUE THREAD

**Issue by nisbus** [keras-rl/keras-rl#255]
When using the Tensorboard callback with histogram > 10 I get this error:

>  File "venv\lib\site-packages\keras\callbacks.py", line 798, in set_model
>     grads = model.optimizer.get_gradients(model.total_loss,
> AttributeError: 'DQNAgent' object has no attribute 'optimizer'

With a histogram set to 0 the model runs as expected.

Is there something I should be doing differently?

My model:

```
 model = Sequential()
        shape = (1, env.parameters)
        model.add(LSTM(units=output_dim,input_shape=shape, return_sequences=True))
        model.add(LSTM(units=output_dim, return_sequences=True))
        model.add(LSTM(units=output_dim))
        model.add(Dense(output_dim, activation='relu'))
        tensor_board = TensorBoard(log_dir="./logs/{}".format(time()), histogram_freq=10, write_graph=True,
                                   write_grads=True, write_images=True)
        return model, tensor_board
```

And my agent:

```
memory = SequentialMemory(limit=1000, window_length=1)
    dqn = DQNAgent(model, nb_actions=output_dim, memory=memory, enable_dueling_network=True, enable_double_dqn=True,
                   policy=EpsGreedyQPolicy(), nb_steps_warmup=5000)
    dqn.compile(optimizer='adam', metrics=['accuracy'])
    dqn.fit(env, nb_steps=10000, callbacks=[tensor_board], visualize=False)
    dqn.save_weights(file, overwrite=True)
    dqn.test(env, nb_episodes=5, callbacks=[tensor_board], visualize=False)
```

What am I missing?

**Comment by AcelisWeaven** [comment]
Have you found a solution, by any chance? I'm having the same issue with LearningRateScheduler and ReduceLROnPlateau.

**Comment by nmelgiri** [comment]
Why is this closed?????? Need help on a very similar issue!!! Just instead of DQNAgent, I'm using CEMAgent.

**Comment by Icemole** [comment]
For some reason that I am not aware of, Keras-RL messes with the reference to your `Model` (in OP's case, the variable `model`) and changes it by a reference to a `DQNAgent`. Then, when accessing the `optimizer` variable the program crashes because `DQNAgent` does not have an `optimizer`. However, the `model` inside it does. Therefore, the most straightforward workaround could be to modify your local `keras/callbacks.py` (you can do it very easily on VSCode by right-clicking the `TensorBoard` constructor and clicking on "Go to definition") and add another `.model` to the offender line:

```
grads = model.model.optimizer.get_gradients(model.model.total_loss,
```

Obviously it's very ugly and also note that you should substitute every occurrence of this in the parts of the library you will need. But if you really want to have the `TensorBoard` functionality then can be an idea.

**Comment by Icemole** [comment]
For some reason that I am not aware of, Keras-RL messes with the reference to your `Model` (in OP's case, the variable `model`) and changes it by a reference to a `DQNAgent`. Then, when accessing the optimizer variable the program crashes because `DQNAgent` does not have an `optimizer`. However, the `model` variable inside it does. Therefore, the most straightforward workaround could be to modify your local `keras/callbacks.py` (you can do it very easily on VSCode by right-clicking the `TensorBoard` constructor and clicking on "Go to definition") and add another `.model` to the offender line:

```
grads = model.model.optimizer.get_gradients(model.model.total_loss,
```

Obviously it's very ugly and also note that you should substitute every occurrence of this in the parts of the library you will need. But if you really want to have the `TensorBoard` functionality then this could be an initial idea.
