### ISSUE TITLE
Optimize for GPU?

### ISSUE THREAD

**Issue by jheffez** [keras-rl/keras-rl#282]
(this is a question, not issue)
Hello, I would like to speed up the training process and managed to get access to a fairly fast CUDA GPU. However, the speed increase, compared to the cpu, is not much. I read online, and its mentioned in the keras-rl examples, that for speed up I need to run in batches. 
Can someone please shed some light how to speed up learning on a GPU? Or better yet, is there a way to optimize for google TPU?

Also, I'd like to change the number of frames from the default 4 to another number. What do I need to change in the following example ( [https://github.com/keras-rl/keras-rl/blob/master/examples/dqn_atari.py](url) )?  Is it just the WINDOW_LENGTH or the model itself (or both)?

Thank you

**Comment by zgrkpnr** [comment]
> for speed up I need to run in batches
Did you try that?

**Comment by jheffez** [comment]
I believe I mentioned that (batches is probably the way) but I don't know exactly how. Can you please point me how to run in batches to better utilize GPU/CPU?
Also, is there a way to optimize keras-rl for google TPU?

**Comment by zgrkpnr** [comment]
@jheffez I would suggest you experiment with `nb_steps`  and  `action_repetition` parameters of fit() method. RL is a little different than supervised learning where we have input and output are at our disposal before beginning training. In RL our inputs are dynamically generated by the environment and our output is not predefined.

That's why I suspect either **action repetition** or **number of training steps** is responsible for **batch like** behaviour of the training session. 

Currently, I don't have access to a GPU to test it, thus I cannot tell exactly which one.

**Comment by bklebel** [comment]
There is actually a parameter `batch_size`, at least in the DQNAgent, with which you can change the number of observations used in a batch for the keras function `train_on_batch()`

If you have a GPU accelerated backend (like tensorflow-gpu) with the cuDNN libraries, that is all you can do with keras-rl, as far as I understand. With it, you do accellerate how fast the observation is passed through your model, when it needs to decide on an action. 
If you have a small model, it will most likely not influence the speed very much, compared to performance gains from a stronger cpu which can run the environment faster. 
I do expect much the same from Google TPU - in order to optimise for that, just use the corresponding optimised backend. 

If you really wanted to parallelise the training on CUDA cores, running multiple agents in environments concurrently (A3C and others), `keraso-rl` is not the way (and I haven't seen the likes). 

regarding other mentions of what could increase speed by utilising the gpu: 
From the class `Agent`: 
> action_repetition (integer): Number of times the agent repeats the same action without
                observing the environment again. Setting this to a value > 1 can be useful
                if a single action only has a very small effect on the environment.

Therefore, action repetition gives you no GPU acceleration, it actually changes how the agent behaves in the environment. 

the `nb_steps` is the number of steps you want to train your agent in one `fit()` run. This has of course a strong impact on what you can learn, but hasn't much to do with batch like behaviour or the GPU

The `window_length` is a parameter which defines how many observations are being taken before an action is performed (or changed from the one before). This is needed for some cases, where a 'still image' does not contain important information an agent needs to perform their task (speeds of moving objects are not part of the information provided).

**Comment by jheffez** [comment]
Thank you for the feedback! One thing I'd like to note, Keras-RL shows for support A3C. @bklebel , are you saying that keras-rl  A3C implementation is ineffective?
Anyone tried using keras-rl A3C (or similar)? Are there any A3C keras-rl examples?

**Comment by bklebel** [comment]
No, I'm abaolutely not saying keras-rls implementation of A3C (or similar) was ineffective (nor that it was inefficient), I'm just saying that if you wanted to run parallel environments on the GPU (in a fashion of one agent + environment per CUDA core), keras-rl is not meant and designed for this, as most of what keras-rl itself does is on the CPU, and only what Keras does within keras-rl may run on the GPU if you are using the corresponding backend. 

In the end, it does not really matter (for GPU speedup) whether you are using a purely sequential way of training (one agent at a time) or a parallel way (A3C, ACER, and the likes) if your bottleneck is the CPU. As the CPU is usually alone in working the environment, this is prone to slow down your training - if you have a tiny model, (and that's all the GPU does), your potential for GPU speedup is equally small. 

In the end, the parallel training schemes are so strong in "absolute time", the time you are actually waiting, because there is simply no CPU which can run at 100 GHz ;)
