### ISSUE TITLE
Environments with no terminal state

### ISSUE THREAD

**Issue by tahaeghtesad** [keras-rl/keras-rl#320]
How should I implement and train a DQNAgent in an environment which doesn't have a terminal state?

`nb_max_episode_steps` treats last steps as terminal, but they are not!

**Comment by John-Almardeny** [comment]
Also here, I would like to keep training the agent all the time, there is no termination. But at the same time, it should predict for future (t+1).
Would ya please give a simple example with DDPG?

**Comment by John-Almardeny** [comment]
Can anybody please refers to how to add interval time between each agent-environment interaction and another? 
Many Thanks.

**Comment by John-Almardeny** [comment]
There should be a new PR for this matter. Where if `nb_steps` is `None`, the implementation in `fit()` should change from `while self.step < nb_steps` to `while self.step < True`.

However, I am not sure about `history` if should still stay there, because it might cause `MemoryError` if not rest every now and then during the infinite iteration.
