### ISSUE TITLE
Examples don't work anymore

### ISSUE THREAD

**Issue by iirekm** [keras-rl/keras-rl#366]
- `AttributeError: module 'keras.backend' has no attribute 'image_dim_ordering'`
- `TypeError: len is not well defined for symbolic Tensors. (activation_4/activation_4/Identity:0) Please call `x.shape` rather than `len(x)` for shape information.`
- with TF >= 2.2.0: `"ModuleNotFoundError: No module named 'tensorflow.contrib'"`
- with TF 2.0.0, 2.1.0: `RuntimeError: dictionary changed size during iteration`

Exact Keras/TF versions in `setup.py` or at least on webpage aren't even listed, but it's important to have exactly the same environment as you during development. You made huuuge effort developing this project, but there are no instructions how to exactly use it.

**Comment by andrei-ars** [comment]
yeah, the same error.
how to fix it?

**Comment by Slyracoon23** [comment]
I had the same problem as @iirekm I solved it by installing the following package versions

- `keras` Version: `2.3.0`
- `tensorflow` Version: `1.14.0`
-  `keras-rl` Version: `0.4.2`

**Comment by AntonioTriguero** [comment]
The answer from @Slyracoon23 solve the problem for me (Google Colaboratory - GPU)

**Comment by bannsec** [comment]
Same issue (and looks like another issue ticket as well). Haven't been able to reproduce fix since tensorflow 1.14.0 wasn't built for python 3.8, so would have to fully build it myself..

Anyone know if this project is getting support in the future? Looks pretty neat but also pretty dead. Unfortunate :(

EDIT: Looks like someone has updated it here: https://github.com/wau/keras-rl2  That's a newer (v2) of tensorflow at least but not the current. I can confirm keras-rl2 at least works on the example dqn though it may have other issues.

**Comment by bannsec** [comment]
One more update since I just found it. If you're just looking to play with and learn RL in an easy environment, I've been blown away by the documentation and support by this project:

https://github.com/DLR-RM/stable-baselines3

It uses pyTorch and is actively maintained and documented. Definitely recommend.
